version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: realestate-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: RealEstateDB
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - realestate-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # .NET Web API
  api:
    build:
      context: .
      dockerfile: src/RealEstate.WebApi/Dockerfile
    container_name: realestate-api
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://admin:password123@mongodb:27017/RealEstateDB?authSource=admin
      - MongoDbSettings__DatabaseName=RealEstateDB
      - MongoDbSettings__OwnersCollectionName=Owners
      - MongoDbSettings__PropertiesCollectionName=Properties
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - realestate-network
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb_data:
    driver: local

networks:
  realestate-network:
    driver: bridge
